### ISSUE TITLE
can not load graph data from hdfs

### ISSUE THREAD

**Issue by lyysdy** [dato-code/PowerGraph#184]
I use --graph hdfs://hostname/path/to/file to load hdfs data.
But it shows the error below

n in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Can't construct instance of class org.apache.hadoop.conf.Configuration
ERROR: hdfs.hpp(hdfs:111): Check failed: filesystem != __null

**Comment by GitZFAN** [comment]
I have met the same problem...

**Comment by GitZFAN** [comment]
But I found this problem can be solved if you used Hadoop v1.0 HDFS.
